### ISSUE TITLE
Cap the amount of players per team

### ISSUE THREAD

**Issue by superjova** [chairleague/hots-rules#1]
Some teams have over 10+ members on their roster.

This makes it hard to:

- Scout your opponent
- Reward teams for winning playoffs
- Figure out who's active

As previously talked about in the rules committee, we should limit the amount of users per team to 8.

Couple of details to be discussed before added:

- How should teams who currently have more than 8 members be slimmed down to the new system?
- When signing up for season, should teams have to slim down their roster before they can join?

**Comment by Durgulach** [comment]
As a Team8 fan on a CL team with 8 players I approve...

In all honesty though if we do the 5/5 no sub rule 8 is as low as some of the older aged teams can reliably feild a team each week.

**Comment by denkstrum-hots** [comment]
I like limiting it to 7 and let off team subs occur.  Keeps it to a core amount of people that you need to scout.  8 seems high to me,  but reasonable.  I think you'll need to allow off team subs or you may have even more cancelled matches in the future.

**Comment by denkstrum-hots** [comment]
As for slimming down teams, limit active slots to those 8 prior to start of season with the roster lock you had in another topic.

**Comment by johnafogarty4** [comment]
I'm actually good with either 7 or 8.  The real determining factor will be how subs work.  Also it would be helpful to have a non-player position to assign people to.  I may only be managing a team this season, and not playing, it would be helpful if i was not counted against the roster, but also not allowed to play.  Not sure if that makes sense or not outside of my head.

**Comment by Durgulach** [comment]
I know 7 would be tough for my guys, we have 4 members with rough work schedules and wives and such that will knock multiple members out on any given week.

For consistency I would rather just have no-sub and an 8 man roster.  If we did 7 man roster and 4/5 it will is basically having an 8 man roster anyway but retains the scouting issues mentioned in OP or makes them worse

**Comment by Akkuma** [comment]
I myself am partial to 7 roster max, 1 sub available at any given time, because shit happens and many teams only need 5 on their roster the majority of the time and an odd random sub every now and then.

**Comment by Durgulach** [comment]
7 members + an unrostered sub is basically a functional roster of 8.  It allows the bigger teams to have 8 members with no restriction and allows the 5ers to have some flexability.  All comes down to whether we go 4/5 roster players per game or 5/5

**Comment by Akkuma** [comment]
No they aren't functionally the same. If you enforce 8 roster members and you lock rosters at a certain point that means you cannot sub someone in. If we do 4/5 then technically you are always allowed a sub at which point I'd say 7. If you force everyone to be on the roster and lock rosters that is problematic to me as you have to have dedicated subs rather than a random sub.

**Comment by Durgulach** [comment]
Right, I was unclear.  I did not mean to say 7 ina 4/5 scheme and 8 in a 5/5 sceme are equvalent.  All I meant was that in a 4/5 scheme you would be able to functionally have an 8 person team with a single person dedicated to filling the sub role.  (Basically for those of us with 8 man rosters due to at least 2-3 people being called away on life 7 in a 4/5 would still be flexible enough)

**Comment by superjova** [comment]
Capped to 8 players. Rules updated.
