### ISSUE TITLE
Master and Grand Masters in Division 3

### ISSUE THREAD

**Issue by superjova** [chairleague/hots-rules#2]
Add a rule to make a restriction for Master and Grand Masters in Division 3.

Rules breakers should be automatically disqualified for the match.

**Comment by Durgulach** [comment]
I support the rule but my main issue here is enforcement, how do we possibly anti-smurf?

**Comment by Ronin89** [comment]
Its true, it is very difficult to enforce this...but its better than nothing.  We should be on the lookout for people who are playing like high skilled vets with only a couple hundred games on their account.

**Comment by Durgulach** [comment]
My inly concern there Ronin, is if someone convinces a LoL buddy to move over and join the league.  He may have mechanics of a master player but not be an actual master.  Or the possible scenario of someone who doesnt play ranked but busts out a killer season.  If we punish that then the rule is over reaching.  That becomes problematic if/when the league starts charging entry.

Ultimately we will need to come up with a process (which could be as simple as Superjova makig a judgment call) to punish smurfing while distinguishing D1 and D2 players from masters.

...and for that matter smurfing should probably be added to the actual language of the rule.

**Comment by denkstrum-hots** [comment]
I don't think you will ever be able to accurately detect and determine smurfing.  I've seen legit gold teams beat diamond teams due to communication and team work.  Since the rule is being extended to any past season HL ranking, would all accounts have to finished placement in the past two seasons?  Doesn't prevent throwing placements, but gives something more verifiable atleast.

**Comment by johnafogarty4** [comment]
Real time enforcement is difficult.  Enforcement after the fact not so hard.  If a team knows this rule exists, and then posts about a team violating the rule in the forums (which we know happens), then we can enforce the rule.

**Comment by Durgulach** [comment]
If they post after the fact and we go look and the player they said is a master is unranked with 100 games played what is the call.

I hugely dislike requiring placement in HL to play in CL.  I have only finished placements in one season in HL due to the fact that I play the actual game only once a week or so and when I am on I am playing with other people, ususally my teammates.

**Comment by Durgulach** [comment]
Besises iifc you cannot place into masters, you can only place as high as Diamond 3

**Comment by Akkuma** [comment]
Here is how you prevent low effort smurfing and verify people:

1. Require linking to their Hotslogs
2. Require anyone looking to play in Chair League have ~100 games played on their account.

You can now manually check if they have more than 100 games and are less likely a smurf account and that they aren't Master or higher.

**Comment by Durgulach** [comment]
There is always the more passive way too... make the rule don't mention smurfing and cross the bridge if/when it comes.  

I am ok with ~100 games, but if it is an antismurf measure it should exclude AI games.

**Comment by pkatz19c** [comment]
I really appreciate the move to protect us Div 3 scrubs. Master may not even be a low enough cut-off; quite honestly, I suspect a high-diamond sub could carry a previously all-silver team far above an all-gold team. If you do want an Easy/Medium/Hard sense with the three brackets, but only Masters is the cutoff for Easy, doesn't that make Division 3 for Bronze/Silver/Gold/Plat/Diamond players? That's a huge range!

**Comment by Durgulach** [comment]
It is a huge range, but that range is also being balanced against the free association of players.  If a diamond player wants to play with his scrub silver irl buddies should they play in Div2 where they are much much more likely to go winless or should they play in Div3

**Comment by pkatz19c** [comment]
That's a fair counterargument.

**Comment by Akkuma** [comment]
@pkatz19c I've had a solution to this for months. Divisions shouldn't be selectable, but an mean/median mmr of your top 5 player mmrs. Each team gets a seed mmr based on that mean/median mmr. The divisions each are divided roughly evenly and wins/losses now impact your team's mmr. This means each season impacts the next season for smarter matchmaking. If you are a team with a seed mmr of 1500 and face off against a 1600 mmr team your win moves you up faster than a single win most likely does, while simultaneously if you lose you shouldn't move as far down.

At the end of each season teams move up/down divisions based on their new mmr. The team's mmr carries over into the next season allowing it to start off in a better place. Matches should also become more competitive by using a mmr system and not win/loss.

In your particular scenario, if you have a Diamond player with 2700 MMR and the rest of the team is 1500, you'd have something like a 1740 MMR using mean or 1500 using median. In comparison if you have a team ranging from 1700 to 1300 (1700, 1600, 1500, 1400, 1300) you'd have a 1500 mmr in either mean or median.

This would mean the higher mmr team is expected to win against many teams (let's say D3 cutoff comes out to be 1800 MMR for the best team), but they'd potentially never face the lower mmr teams.

**Comment by Durgulach** [comment]
Where does your MMR come from though?  HotsLogs isnt accurate as far as MMR goes, Blizz mmr isnt available (though that may have changed with the 2.0 api?),  do you use the TL rank mmr, HL, UD, QM?  What is to prevent smurfing under an MMR system?  Or unintentional sandbagging from a Diamond and silver squad that beats an all gold squad too easily?

Take me for example:  this season HL unranked 0 placements played, TL silver 5.  Last season: HL placed Gold 2, only played placements to see whwre I would land in solo q, TL Bronze 1.  That is all over the place, what MMR do you draw from that?

Doesnt your system really just make a new version of a TL ladder?  Isnt that what we want to avoid?

**Comment by Akkuma** [comment]
Hotslogs MMR is more accurate than any system CL has in place, which is literally 0 form of MMR and 30-40 teams in a single division meaning you play less than 30% of the teams to prove you're good enough for the playoffs. I already proposed a minimum amount of games before a player is eligible to play in CL to prevent smurf accounts.

You'd use HL -> UD -> QM or you use the median MMR.

> Or unintentional sandbagging from a Diamond and silver squad that beats an all gold squad too easily?

This isn't sandbagging if the teams are rather close in MMR and you can still implement forced cutoffs that if a team's mmr would put them in D3, but have a Diamond player they are forced up to D2. This was already discussed with no GM/Masters in D3.

There is no such thing as a real TL ladder, since there are no teams on the TL ladder, only individuals. Additionally, this isn't a ladder. It is ladder-like, but that is because people want to play matches that are fair. You still slice it up into divisions and can still have division playoffs. 

We have people wanting to prevent smurfs and high mmr players from playing in D3. What about D2 teams with all low golds vs a full mid plat team? Does that sound fair? The current system and even the suggestions offered outside of mine will still result in this sort of match in D2.

**Comment by superjova** [comment]
Chair League is not integrating HotsLogs MMR. We can stop discussing that as a potential solution

**Comment by Akkuma** [comment]
Teams should still have a real rating system that carries across season to season. Whether you want to homebrew your own or not is entirely unimportant.

**Comment by superjova** [comment]
There is a season rating which you see in the standings, and there's a team rating you can find on the team's profile page. You could limit teams from joining divisions based on that rating. For example, 1700 team Brawls Deep shouldn't be able to sign up for Division 3.

Users could also get a rating based on playing with teams. Similar to how WoW arena rankings worked long ago.

One thing to remember is that Chair League is a rec league. It should feel like a rec league for video games. When I think about college rec leagues I joined, they never asked what level of soccer did I play previously. They gave us 2 options: competitive and recreational divisions to choose from. We picked the one we thought our team could compete at. Out of 8 seasons we only won the playoffs once. Nobody tried to limit us or confine us from playing in certain divisions. Our team changed from year to year as people graduated or got too fat from all the beer.

**Comment by Akkuma** [comment]
I think there should only be 1 rating, a team rating and that rating is used for everything. A team's rating adjusts across seasons, but does each season take a team's rating into account at all? The results of a team with 1500 rating vs 1600 rating should net quite a bit of +/-, but as it stands wins and loses last I saw are almost always the same regardless of who you play. Are team ratings being used for anything in terms of MM?

My previous suggestions did not prevent people from playing with who they want, it just prevented potentially unfair matches from happening, Clearly people at the very least feel master+ should be banned from D3 and I think that is fair as it is too far away to even try balancing via a rating system of any sort.

**Comment by superjova** [comment]
Closing rules updated.
